//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CarTbl
    {
        public int CarID { get; set; }
        [Display(Name = " Car Brand")]
        public int BrandID { get; set; }
        [Display(Name = "Model")]
        public string CarName { get; set; }
        [Display(Name = "Technical Characteristics")]
        public string TechnicalCharacteristics { get; set; }
        public string Properties { get; set; }
        public byte[] Image { get; set; }
        [Display(Name = "Number in Stock")]
        public Nullable<int> NoStock { get; set; }

        [Display(Name = "Brand")]
        public virtual BrandTbl BrandTbl { get; set; }
    }
}
